### ISSUE TITLE
about the local deployment

### ISSUE THREAD

**Issue by Mr-KID-github** [dvlab-research/LISA#11]
Will there be an on-premises release? If so when will it be?

**Comment by X-Lai** [comment]
Yes, we plan to release the code of local deployment next week, please stay tuned.

**Comment by Mr-KID-github** [comment]
ok looking forward

**Comment by X-Lai** [comment]
Hi, we have released the code for local deployment: https://github.com/dvlab-research/LISA#deployment. Welcome to check it out!
