### ISSUE TITLE
Compute requirement

### ISSUE THREAD

**Issue by ajinkya123-robo** [dvlab-research/LISA#13]
Hello, Excellent work by the team. May I know what sort of computational resources (no. of GPUs, RAM etc.) I will require for both reproducing this (LISA) and further fine tuning. Thanks

**Comment by X-Lai** [comment]
For the 7B model, training can be done with 8 * 3090 GPUs (24GB VRAM) (actually, the number of GPUs can be lowered by increasing the `grad_accumulation_steps` as long as you make sure `grad_accumulation_steps * num_GPUs * batch_size` keeps the same). For training the 13B model, currently, you may need GPUs with no less than 40GB.

**Comment by ajinkya123-robo** [comment]
Thank you for quick reply!
