### ISSUE TITLE
How are validation images excluded for RefCOCO?

### ISSUE THREAD

**Issue by yxchng** [dvlab-research/LISA#15]
It seems like this variable https://github.com/dvlab-research/LISA/blob/8d5edb43e89d13186ff8e561ceea45eb49e288c9/utils/refer_seg_dataset.py#L43 is not being used in the code. Which part of the code exclude the validation images?

What about the test images? Are they excluded as well?

**Comment by X-Lai** [comment]
The released version is refactored from our experimental codebase. To ensure code readability, we do not refactor this part (so please ignore the variable `exclude_val`).  

FYI, for the experiments of Table 2 in our paper, we exclude both validation and testing images of refCOCO series data for a fair comparison.

**Comment by yxchng** [comment]
@X-Lai so does that mean that this codebase currently does not remove val?
