### ISSUE TITLE
Training on Pretrained LISA Model

### ISSUE THREAD

**Issue by Mactor2018** [dvlab-research/LISA#159]
Hello, and thank you for your excellent work! I am currently working on training a downstream task using LISA, but I’m unsure about the correct approach for training on the pretrained LISA model.

I’ve attempted to use your pretrained LISA model as the Llama2 model, and I've also implemented SAM ViT-H pretrained weights. Here’s the command I used:

```bash
deepspeed --master_port=24999  --include localhost:0,1  train_ds.py \
  --version="./model/LISA-13B-llama2-v1/" \
  --dataset_dir='./dataset/' \
  --vision_pretrained="./model/sam_vit_to_train/sam_vit_h.pth" \
  # other args...
```

However, I noticed that the model's performance isn’t very good after training for 5 epochs, which makes me wonder if I have **correctly** set up training with your **pretrained** model.

Could you please confirm if this setup is correct or suggest any modifications? Thank you!

**Comment by Mactor2018** [comment]
I checked and compared the `train_ds.py` and `chat.py` and find that the training code might have to be modified to load the llama and SAM from one source together, like that in inference.

**Comment by BoyangLi21** [comment]
> I checked and compared the `train_ds.py` and `chat.py` and find that the training code might have to be modified to load the llama and SAM from one source together, like that in inference.

Modifiy model.get_model().initialize_lisa_modules(model.get_model().config) in train_ds.py, make sure it does not load original sam weight while you have already loaded sam from LISA.
Hope that helps
