### ISSUE TITLE
Training Log

### ISSUE THREAD

**Issue by Noietch** [dvlab-research/LISA#19]
May I ask if you could provide the training log information? Additionally, we have noticed slower training speeds on 8 V100 GPUs. We are unsure of the reason for this.

**Comment by X-Lai** [comment]
Sorry, we do not save the training log into files. May I know how long it takes for one training step?

**Comment by Noietch** [comment]
For the V100, each step takes about 2 minutes. We suspect it might be a data precision issue. Initially, we opted for BF16, but V100 doesn't support training with BF16. It's possible that DeepSpeed automatically converted it to float32. Afterward, we switched to half-precision, and each step now takes around half a minute.

**Comment by X-Lai** [comment]
We haven't tried training on V100. But we could provide some statistics on 3090. For 13B model, one step takes around 30 seconds on bf16 for 8 * 3090 GPUs.

**Comment by yxchng** [comment]
@Noietch have you solved the problem? i am also meeting the same issue, taking 2 minutes per step.
