### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by fujianhai** [dvlab-research/LISA#20]
when i trying to load a model using local model：
we use this local model ： https://huggingface.co/xinlai/LISA-13B-llama2-v0/tree/main

LlavaLlamaForCausalLM.from_pretrained(pretrained_model_name_or_path="xxx/xxx/LISA-13B-llama2-v0")

it result in :

```
loading checkpoint shards: 0% 
*** OSError :/ UNanable to load weights from pytorch checkpoint file for
 "xxx/xxx/LISA-13B-llama2-v0/pytorch_model-00001-of-00003.bin“ 
at ”xxx/xxx/LISA-13B-llama2-v0/pytorch_model-00001-of-00003.bin“ .
 If you tried to load a pytorch model from a TF 2.0 checkpoint ,please set from_tf=True
```

torch2.0.1，torchvision0.15.2,cuda 11.7, python3.8, and DeepSpeed 0.9.0.

**Comment by X-Lai** [comment]
It seems that the files are broken. Can you check whether it is downloaded successfully?

**Comment by fujianhai** [comment]
> It seems that the files are broken. Can you check whether it is downloaded successfully?

yes, now is ok,  thank you
