### ISSUE TITLE
Failed to download saiapr_tc-12 dataset

### ISSUE THREAD

**Issue by wangjunchi** [dvlab-research/LISA#22]
Hi

Thank you for your impressive work. I am wondering if it is possible to share the saiapr_tc-12 dataset using something like Google Drive. The download speed of web archive is extremely slow and unstable. It took me many hours but I still failed to download it.

**Comment by X-Lai** [comment]
You can download here: https://mycuhk-my.sharepoint.com/:f:/g/personal/1155154502_link_cuhk_edu_hk/Em5yELVBvfREodKC94nOFLoBLro_LPxsOxNV44PHRWgLcA?e=zQPjsc

Also, note that anyone downloading files here must follow the rules that the original datasets require.

**Comment by wangjunchi** [comment]
Thank you for your sharing! 
Also for anyone having the same issue: You can either download the saiapr_tc-12.zip using the link above, or you can download the original dataset from https://www.imageclef.org/SIAPRdata and unzip everything.  The original dataset contains the benchmark/saiapr_tc-12 which is the same as the saiapr_tc-12.zip.
