### ISSUE TITLE
Confidence for Masks?

### ISSUE THREAD

**Issue by shivam-chandhok** [dvlab-research/LISA#26]
Is there any confidence value I can get corresponding to the object found.
For example in case of multi objects detected for a given prompt, how can I choose the most probable one.

**Comment by X-Lai** [comment]
Do you mean the prediction mask before sigmoid? In the current implementation, we do not differentiate between multiple objects or a single one. All of them are represented by a single binary mask.

**Comment by Tetsujinfr** [comment]
> Is there any confidence value I can get corresponding to the object found. For example in case of multi objects detected for a given prompt, how can I choose the most probable one.

you may want to not highlight more than one type of objects at a time though, I have observed that the longer/complex the prompt is, the less effective/accurate the mask output. for instance below images output for 2 different prompts:

`Can you segment cars?`
![test5_Can you segment cars?](https://github.com/dvlab-research/LISA/assets/29961693/ccc2b719-7fe3-427e-bb65-d0c936662759)

`Can you segment humans and animals and balls and cars and trucks and buses and motorbikes and bicycles and airplanes?`
![test5_Can you segment humans and animals and balls and cars and trucks and buses and motorbikes and bicycles and airplanes?](https://github.com/dvlab-research/LISA/assets/29961693/6fe71fc1-e916-431f-bec3-ad48f7490e20)
