### ISSUE TITLE
About the inference model

### ISSUE THREAD

**Issue by xiaozhen228** [dvlab-research/LISA#27]
when I use "CUDA_VISIBLE_DEVICES=0 python3 chat.py --version='xinlai/LISA-13B-llama2-v0' --precision='fp16' --load_in_4bit
", there is an error:

self.mlp_output_mp(mp_replace, reversed_dim=reversed_dim)
  File "/home/user/miniconda3/envs/python_3.9/lib/python3.9/site-packages/deepspeed/module_inject/containers/base.py", line 257, in mlp_output_mp
    self.module.mlp.output_w = mp_replace.copy(self.module.mlp.output_w, self._4hh_w, int8=reversed_dim)
  File "/home/user/miniconda3/envs/python_3.9/lib/python3.9/site-packages/deepspeed/module_inject/auto_tp.py", line 97, in copy
    self.merge_assert(src_shape[inner_dim], dst_shape[self.in_dim])
  File "/home/user/miniconda3/envs/python_3.9/lib/python3.9/site-packages/deepspeed/module_inject/auto_tp.py", line 31, in merge_assert
    assert dim1 > dim2, \
AssertionError: Merging tensors is not allowed here! Please use deepspeed load_checkpoint            for merging your checkpoints before replacing the transformer layer with            inference-kernels

**Comment by LWShowTime** [comment]
> May I know if you have successfully downloaded the model? Have you modified the code?
> 
> Besides, can you give more detailed error info?

Same problems met. I download the CLIP and the LLAMA to local. So I modified the version args and the vision_towers args to the local dir. However, I didn't figure out where the mm_vision_tower is set. So I change the line55 in llava.py.
![image](https://github.com/dvlab-research/LISA/assets/51390653/50051978-6236-4437-a534-c88ff0c7165a)

**Comment by X-Lai** [comment]
To use `chat.py`, you should use the model of `xinlai/LISA-13B-llama2-v0-explanatory` or `xinlai/LISA-13B-llama2-v0` as for the `version` argument, rather than LLAMA.

**Comment by LWShowTime** [comment]
> To use `chat.py`, you should use the model of `xinlai/LISA-13B-llama2-v0-explanatory` or `xinlai/LISA-13B-llama2-v0` as for the `version` argument, rather than LLAMA.

Yes, I use that two pretrained model. Not llama, sorry I spell the wrong one. I use this link:
https://huggingface.co/xinlai/LISA-13B-llama2-v0-explanatory
