### ISSUE TITLE
training data size/volume

### ISSUE THREAD

**Issue by qinqingegee** [dvlab-research/LISA#28]
Hello! I would like to know the approximate amount of data in the datasets of segmentation, referring segmentation, and VQA, ie, the number of images, masks, and instructions. Thanks!

**Comment by X-Lai** [comment]
The semantic segmentation data contains around 200k images and multi-class labels. The referring segmentation data contains about 20k images, but each is annotated with multiple text queries. For VQA data, we use the llava-instruct-150k dataset, which contains 150k question-answer pairs.
