### ISSUE TITLE
--load_4bit is much slower than --load_8bit

### ISSUE THREAD

**Issue by LWShowTime** [dvlab-research/LISA#29]
The loading speed is quite slow..... My question is why the load_4bit load the LLM much more slowly...?

**Comment by LWShowTime** [comment]
My question is why 4bit load the model quite slow than 8bit?

**Comment by LWShowTime** [comment]
> Hi, we have updated the script and the model. Can you try the new version?

@X-Lai Okay, good to hear that. Another question, it seems like change the args.vision_tower doesn't work. 我是直接在llava.py第55行手动写死本地路径才行。config变量的mm_vision_tower究竟在哪里可以设置？
![image](https://github.com/dvlab-research/LISA/assets/51390653/eb608348-a55a-440c-9278-56c63909aa96)

**Comment by X-Lai** [comment]
在你现在使用的这个版本里面，目前只能通过这种方式来更改vision_tower，这也是LLaVA的上一版代码的遗留问题。如果你方便的话，可以使用我们最新版本的代码，可以直接通过参数来替换vision_tower。

**Comment by LWShowTime** [comment]
> 在你现在使用的这个版本里面，目前只能通过这种方式来更改vision_tower，这也是LLaVA的上一版代码的遗留问题。如果你方便的话，可以使用我们最新版本的代码，可以直接通过参数来替换vision_tower。

@X-Lai 确实看到了，在这里可以实现更改
![image](https://github.com/dvlab-research/LISA/assets/51390653/d21291d0-48ba-4ea7-9546-4f2f6475f9f4)

**Comment by LWShowTime** [comment]
另外，貌似4-bit我没办法再用了。
![image](https://github.com/dvlab-research/LISA/assets/51390653/c558c82a-7b01-4580-a25c-cd0f8fe8bbdb)
