### ISSUE TITLE
Image preprocess

### ISSUE THREAD

**Issue by WPH-commit** [dvlab-research/LISA#3]
Hi, I notice that the image input for LLM goes through the CLIP-preprocessor which involves a center-crop operation. Therefore, some visual information for LLM might be discarded, would this affect the segmentation result if the target is not contained or only partially contained in the center-crop region?

**Comment by X-Lai** [comment]
Thank you for pointing out this issue. It does happen in the current configuration but we do not very likely observe that. In this case, the multi-modal LLM obtains some clues solely from the text instruction and can influence the segmentation result. 

However, we directly follow the configuration from LLaVA, and potentially LLaVA also possesses this problem. This may be avoided by resizing the longest side to 224.
