### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by Noietch** [dvlab-research/LISA#4]
When will the training code be released?

**Comment by X-Lai** [comment]
It should be released a day or two later. Please stay tuned.

**Comment by Noietch** [comment]
and when will the 7-b model be released?

**Comment by X-Lai** [comment]
Yes, we will release all of them ASAP.

**Comment by yahooo-m** [comment]
looking forward to it!

**Comment by X-Lai** [comment]
Training code is released now. Welcome to check it out!

BTW, we are also refactoring the training code with Hugging Face Trainer. We will also release it ASAP if everything goes well.
