### ISSUE TITLE
The necessity of the VQA dataset.

### ISSUE THREAD

**Issue by MT-nuo** [dvlab-research/LISA#47]
Nice work!!
In Table 5, why the VQA dataset is not ablated？
The paper explains that "To preserve the original Visual Question Answering (VQA) ability of the multi-modal LLM, we also include the VQA dataset during training." 
In other words, when there is no need to explain the reason for result and only locate the target object, whether the VQA dataset is required.

**Comment by X-Lai** [comment]
We haven't tried that before. But I think that VQA data does not matter that much if we only focus the segmentation performance.
