### ISSUE TITLE
The online demo seems not good

### ISSUE THREAD

**Issue by linhaojia13** [dvlab-research/LISA#49]
Thank you for opening your work! 
I tested three examples, but LISA didn't provide the correct responses. These examples weren't cherry-picked to find the weakness of LISA;  I just randomly picked them from the internet."
![图片](https://github.com/dvlab-research/LISA/assets/38275612/7c94dd8d-1253-468b-bee7-29404fb0264b)
![图片](https://github.com/dvlab-research/LISA/assets/38275612/7f21a049-6368-40ea-aeeb-8f34c4ad670a)
![图片](https://github.com/dvlab-research/LISA/assets/38275612/8bd1f109-1f23-4b7a-ad53-d5c85224af06)

**Comment by X-Lai** [comment]
Yes, thanks for reporting this. Honestly speaking, there exist many failure cases. The potential reasons can be insufficient training data or unstable performance of the base model (e.g., LLaVA). 

According to our observation, when the input text query is ambiguous or not that certain, the model is more likely to fail or output some artifacts. However, when the input text query is regulated or has the only answer, the model is more likely to make predictions correctly.
