### ISSUE TITLE
ADE20K Dataset Preparation

### ISSUE THREAD

**Issue by hanoonaR** [dvlab-research/LISA#50]
Dear Authors, 

Thanks for sharing your great work. 

Can you please share the details of how to prepare the ADE20K dataset?
 The original dataset contains segmentation masks '.png files' with labels of more than 150 categories, giving an error when running [`classes = [self.data2classes[ds][class_id] for class_id in unique_label]`](https://github.com/dvlab-research/LISA/blob/d4050d9affcda9e6d759d010b806784eae91fdab/utils/sem_seg_dataset.py#L267).
 
Thank you.

**Comment by X-Lai** [comment]
Can you give more detailed error?

**Comment by hanoonaR** [comment]
Thank you for the quick response. 

Some context on how the data is downloaded and its format: When the dataset is downloaded from the official [website](https://groups.csail.mit.edu/vision/datasets/ADE20K/), it has the following structure:
|── images
│   └── ADE
│       ├── training
│       │   ├── cultural
│       │   │   ├── apse__indoor
│       │   │   │   ├── ADE_train_00001472
│       │   │   │   │   ├── instance_000_ADE_train_00001472.png
│       │   │   │   │   ├── instance_001_ADE_train_00001472.png
│       │   │   │   │   ├── instance_002_ADE_train_00001472.png
│       │   │   │   │   ├── instance_003_ADE_train_00001472.png
│       │   │   │   │   ├── instance_004_ADE_train_00001472.png
│       │   │   │   │   ├── instance_005_ADE_train_00001472.png
│       │   │   │   │   ├── instance_006_ADE_train_00001472.png
│       │   │   │   │   └── instance_007_ADE_train_00001472.png
│       │   │   │   ├── ADE_train_00001472.jpg
│       │   │   │   ├── ADE_train_00001472.json
│       │   │   │   ├── ADE_train_00001472_seg.png

The [dataset](https://github.com/dvlab-research/LISA/blob/d4050d9affcda9e6d759d010b806784eae91fdab/utils/sem_seg_dataset.py#L39) in your project requires all images of '.jpg' to be together within the images folder and all '.png' images to be in the annotation folder. 

The major issue is that the '.png' files have more than 150 category labels in it, while the number of categories is 150. Is there some pre-processing that I am missing? 

When [`unique_label`](https://github.com/dvlab-research/LISA/blob/d4050d9affcda9e6d759d010b806784eae91fdab/utils/sem_seg_dataset.py#L261C13-L261C53) is computed, it has values from 0 to 255:
`unique_label = [0, 5, 10, 28, 47, 57, 80, 85, 110, 113, 142, 162, 170, 181, 191, 195, 198, 227, 255]`. While the classes prepared from [utils/ade20k_classes.json](https://github.com/dvlab-research/LISA/blob/d4050d9affcda9e6d759d010b806784eae91fdab/utils/sem_seg_dataset.py#L40C16-L40C41) have only 150 classes, causing indexing errors for values greater than 150
`classes = [self.data2classes[ds][class_id] for class_id in unique_label]`,  [here](https://github.com/dvlab-research/LISA/blob/d4050d9affcda9e6d759d010b806784eae91fdab/utils/sem_seg_dataset.py#L267C13-L267C85).

Any insights into what is the issue would be really helpful. Thank you.

**Comment by X-Lai** [comment]
The dataset that you download is another version of ADE20K. We recommend directly downloading from the link in the readme file. (ADE20K: http://data.csail.mit.edu/places/ADEchallenge/ADEChallengeData2016.zip)
