### ISSUE TITLE
some question for reproduct the result

### ISSUE THREAD

**Issue by xbkaishui** [dvlab-research/LISA#53]
Hello,
I'm attempting to reproduce the performance data from the paper. I currently have only four GPUs and I have a few questions:
1. How much of a performance difference is there between SAM's "huge" model and the "large" model?
2. Approximately how much data should I run to achieve convergence with the model? also the train hours 
3. Would it be possible for you to share the training logs from your experiments ?

Thanks

**Comment by X-Lai** [comment]
1. We haven't tested the SAM-large model.
2. Using the datasets we mentioned is enough. Training on 8*3090 GPUs consumes 3 days or so for a 7B model.
3. We do not save the training logs during training :(, sorry for that
