### ISSUE TITLE
Question about Result Reproduction 

### ISSUE THREAD

**Issue by jiawen-zhu** [dvlab-research/LISA#56]
Hi~, great work.
I run the Validation code using LISA-7B-v1, and get the gIoU and cIoU scores of the ReasonSeg_val `giou: 0.0610, ciou: 0.0567`, which are abnormal and far behind the results in paper. Could you tell me what the problem might be? Thank~

**Comment by X-Lai** [comment]
I think you may not successfully load the model. The validation results seem to be that of random model weights.

Besides, the `v1` model is trained with both `train+val` sets, so please use the v0 model if you want to reproduce the validation results.

**Comment by jiawen-zhu** [comment]
Yes, I find the output mask is random. I download the provided model and valite by:
`deepspeed --master_port=24999 train_ds.py \
  --version="model/llava/pretrain_model/LLaVA-7B-Lightening-v1-1"  \
  --dataset_dir='./dataset' \
  --vision_pretrained="model/segment_anything/pretrained_model/sam_vit_h_4b8939.pth" \
  --exp_name="test" \
  --dataset="reason_seg" \
  --weight='model/lisa/LISA-7B-v1' \
  --eval_only`

But I run the demo by:
`python chat.py --version='model/lisa/LISA-7B-v1' --precision='fp16' --load_in_4bit`
the output mask looks fine. Is my validation cmd wrong?

**Comment by jiawen-zhu** [comment]
In fact, what confuses me is that the validation code sets the `--weight `hyperparameter but I can't found the place where it is uesed.

**Comment by GiscardBiamby** [comment]
Hi, thanks for the great project!

I am having the same issue trying to reproduce the results on reason_seg. I get values like `giou: 0.0843, ciou: 0.0662`. I have tried with the following commands. Can you let me know what I am doing wrong? 

I understand from the previous comment that v1 is trained on train+val, but that makes my results still very unexpected. I should be getting results much higher than this with either v0 or v1. 


```bash

CUDA_VISIBLE_DEVICES="0,3" deepspeed \
    --master_port=24999 \
    train_ds.py \
    --vision_pretrained checkpoints/sam_vit_h_4b8939.pth \
    --weight checkpoints/LISA-13B-llama2-v1/pytorch_model.bin \
    --version checkpoints/LISA-13B-llama2-v1/ \
    --dataset_dir dataset/ \
    --eval_only \
    --dataset reson_seg >> ./output/LISA-13B-llama2-v1.log


CUDA_VISIBLE_DEVICES="0,3" deepspeed \
    --master_port=24999 \
    train_ds.py \
    --vision_pretrained checkpoints/sam_vit_h_4b8939.pth \
    --weight checkpoints/LISA-13B-llama2-v1-explanatory/pytorch_model.bin \
    --version checkpoints/LISA-13B-llama2-v1/ \
    --dataset_dir dataset/ \
    --eval_only \
    --dataset reson_seg >> ./output/LISA-13B-llama2-v1-explanatory.log

CUDA_VISIBLE_DEVICES="0,3" deepspeed \
    --master_port=24999 \
    train_ds.py \
    --vision_pretrained checkpoints/sam_vit_h_4b8939.pth \
    --weight checkpoints/LISA-7B-v1/pytorch_model.bin \
    --version checkpoints/LISA-7B-v1/ \
    --dataset_dir dataset/ \
    --eval_only \
    --dataset reson_seg > ./output/LISA-7B-v1.log


CUDA_VISIBLE_DEVICES="0,3" deepspeed \
    --master_port=24999 \
    train_ds.py \
    --vision_pretrained checkpoints/sam_vit_h_4b8939.pth \
    --weight checkpoints/LISA-7B-v1-explanatory/pytorch_model.bin \
    --version checkpoints/LISA-7B-v1/ \
    --dataset_dir dataset/ \
    --eval_only \
    --dataset reson_seg > ./output/LISA-7B-v1-explanatory.log
```

**Comment by X-Lai** [comment]
Sorry for the confusion, please use the repo of the previous version with `git checkout 0e26916` first and use the `v0` version model.

**Comment by SxJyJay** [comment]
@jiawen-zhu @GiscardBiamby @X-Lai  I have the same issue. I have tried the latest version and `0e26916`, while both of the results are abnormal. (latest: giou: 0.0317, ciou: 0.0200) (`0e26916`: giou: 0.0487, ciou: 0.0309). Have you successfully reproduce the validation performances? How do you solve the issue? Thanks a lot!

**Comment by yxchng** [comment]
@SxJyJay what command do you use?

**Comment by ryusaeba** [comment]
Hi @X-Lai, I just found I can get meaningful accuracy after comment out [this initialization](https://github.com/dvlab-research/LISA/blob/main/train_ds.py#L164). This initialization will make SAM and projection layer from pretrained coefficient to random initialization one.
BEFORE
   giou: 0.0723, ciou: 0.0686
AFTER
   giou: 0.9526, ciou: 0.9721
Please confirm if my understanding is correct.

**Comment by ryusaeba** [comment]
> I think you may not successfully load the model. The validation results seem to be that of random model weights.
> 
> Besides, the `v1` model is trained with both `train+val` sets, so please use the v0 model if you want to reproduce the validation results.

One thing to confirm. As [default setting](https://github.com/dvlab-research/LISA/blob/main/train_ds.py#L60) in training code shows, it looks like it  use `train` sets only. Is my understanding correct? If so, may I know why did v1 use `train+val` sets?

**Comment by Jeff001128** [comment]
> Hi @X-Lai,
> 
> In [4b17762](https://github.com/dvlab-research/LISA/commit/4b1776203d3410cd71b2d4720fc7d9cc61d1db3c) version, I just found I can get meaningful accuracy for xinlai/LISA-13B-llama2-v1-explanatory after comment out [this initialization](https://github.com/dvlab-research/LISA/blob/main/train_ds.py#L164). This initialization will make SAM and projection layer from pretrained coefficient to random initialization one. BEFORE giou: 0.0723, ciou: 0.0686 AFTER giou: 0.9526, ciou: 0.9721 Please confirm if my understanding is correct.
> 
> Should we add a flag for this initialization? `if not args.eval_only: ` ` model.get_model().initialize_lisa_modules(model.get_model().config)`
> 
> Best, Ryusaeba

Hi, thanks for the solution! I also gained a great increase after commenting. However, my result is giou: 0.8833, ciou: 0.9409, and before mine was also lower than yours. What do you think could be the problem? Thanks!

**Comment by Jeff001128** [comment]
> > Hi @X-Lai,
> > In [4b17762](https://github.com/dvlab-research/LISA/commit/4b1776203d3410cd71b2d4720fc7d9cc61d1db3c) version, I just found I can get meaningful accuracy for xinlai/LISA-13B-llama2-v1-explanatory after comment out [this initialization](https://github.com/dvlab-research/LISA/blob/main/train_ds.py#L164). This initialization will make SAM and projection layer from pretrained coefficient to random initialization one. BEFORE giou: 0.0723, ciou: 0.0686 AFTER giou: 0.9526, ciou: 0.9721 Please confirm if my understanding is correct.
> > Should we add a flag for this initialization? `if not args.eval_only: ` ` model.get_model().initialize_lisa_modules(model.get_model().config)`
> > Best, Ryusaeba
> 
> Hi, thanks for the solution! I also gained a great increase after commenting. However, my result is giou: 0.8833, ciou: 0.9409, and before mine was also lower than yours. What do you think could be the problem? Thanks!

Apologies. I used the 7B model hence obtaining lower results. By the way, I've tried to evaluate the 13B model with 8*NVIDIA 3090 GPUs, while met the 'cuda out of memory' error. May I know how many GPUs did you use to evaluate the 13B model @ryusaeba ? Thanks in advance.

**Comment by ryusaeba** [comment]
@Jeff001128 Yes, you are right. I'm using 13B.

**Comment by baibizhe** [comment]
same here. when i use LISA-13B-llama2-v0 with 0e26916 on reason_seg. the tensorboard logs 0.06295.  
using LISA-13B-llama2-v1 on  main will result around 0.9 . how to reproduce the result on paper ?

**Comment by wyn-Mandy** [comment]
> I think you may not successfully load the model. The validation results seem to be that of random model weights.我认为你可能没有成功加载模型。验证结果看起来像是随机模型权重。
> 
> Besides, the `v1` model is trained with both `train+val` sets, so please use the v0 model if you want to reproduce the validation results.此外， `v1` 模型是用 `train+val` 两个数据集训练的，所以如果你想要复现验证结果，请使用 v0 模型。

How can I get the LISA-7B-v0 model？I only find the LISA-7B-v1 in your huggingface. Do I need to train it by myself？
I tried to train LISA-7B-v0 in 4090, but the iou is only 0.002 after 10 epoch (500 step/epoch). 
Could you give me some giudence? Thank you!
