### ISSUE TITLE
Gradient accumulation in Training

### ISSUE THREAD

**Issue by zamling** [dvlab-research/LISA#58]
Hi~
I found model.step() is in the grad_accumulation_steps loop
https://github.com/dvlab-research/LISA/blob/main/train_ds.py#L472

Does this mean the gradient accumulation not work?

**Comment by X-Lai** [comment]
Hi, `model.step()` actually is called by functions provided by deepspeed, and it will automatically updates its parameters every `grad_accumulation_steps` steps.

**Comment by Shaosifan** [comment]
> Hi, `model.step()` actually is called by functions provided by deepspeed, and it will automatically updates its parameters every `grad_accumulation_steps` steps.

Sorry, I still do not understand. Can you explain more about this? Thanks.
