### ISSUE TITLE
RefVOS evaluation

### ISSUE THREAD

**Issue by dengandong** [dvlab-research/LISA#61]
Hi there,

 In your Table 2, did you only train on RefVOS dataset, or still using the Hybrid dataset?

You mentioned, "We evaluate the methods on refCOCO, refCOCO+, refCOCOg validation and testing sets." Since the Hybrid dataset is also an important contribution, I'm not sure whether "the method" contains it or not.

**Comment by X-Lai** [comment]
Hi, we do not use RefVOS dataset. The hybrid dataset contains the training datasets of refCOCO, refCOCO+, refCOCOg.
