### ISSUE TITLE
Issues to run deployment app.py 

### ISSUE THREAD

**Issue by yxu1168** [dvlab-research/LISA#62]
Hi Xin,

I am trying to run deployment app.py
when run your code "CUDA_VISIBLE_DEVICES=0 python app.py --version='xinlai/LISA-13B-llama2-v1' --load_in_4bit"
it shows ' 2023-09-28 22:49:28.525052: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT' , Do you must use NVIDA TensorRT? Does TensorRT installed on your server? Any other replacement for TensorRT?

If I run this app.py in Cloud, should I remove '--load_in_4_bit'?

When it continues to run the app.py, it ends up with:
Downloading (…)l-00003-of-00003.bin: 100% 8.86G/8.86G [00:54<00:00, 162MB/s]
Downloading shards: 100% 3/3 [03:17<00:00, 65.93s/it]
Downloading (…)lve/main/config.json: 100% 4.52k/4.52k [00:00<00:00, 16.7MB/s]
Loading checkpoint shards:   0% 0/3 [00:00<?, ?it/s]^C

What happened here? How can I make it finish the running?
Thanks a lot for help.
Regards,

Dan

**Comment by X-Lai** [comment]
Hi, we didn't use TensorRT. If you use `--load_in_4bit`, please also include `--precision='fp16'`. 

Besides, when it continues to run, it will automatically download the models from huggingface. So just wait until it finishes downloading.

**Comment by yxu1168** [comment]
Hi Xin,

Thank you very much for your prompt response.
It is interesting that you didn't use TensorRT but the machine is looking for it.
My computer doesn't have GPU, I was using Colab's GPU. When I install the requirements, I also got error message:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible. torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 1.13.1+cu117 which is incompatible. torchdata 0.6.1 requires torch==2.0.1, but you have torch 1.13.1+cu117 which is incompatible. torchtext 0.15.2 requires torch==2.0.1, but you have torch 1.13.1+cu117 which is incompatible.

However, the Colab still ran the app.py. The Colab couldn't handle large file download so it stopped. I will add --precision = 'fp16', and may try it in Cloud.
It is very interesting that finetune your pretrained model for some specific tasks. I am wondering how you freeze the encoder and train the decoder? In your model weights, do you have a configuration file to setup the encoder to be frozen?
Hope can learn more from you. Thanks a lot.
Best regards,

Dan
________________________________

**Comment by AmrinKareem** [comment]
Hi, did you figure out the finetuning configurations?

**Comment by yxu1168** [comment]
Hi Amrin,

No. Need to know where to freeze encoders and annotate your data. Did you figure out how to finetune LISA?
Now run deployment app.py at Colab is good.

Hi Xin,
Since you have finetuned LISA with ReasonSeg dataset, can you please teach us steps or add new content of finetune in your Github repo?
I am also interested in Zero-Shot. You mentioned LISA has robust Zero-Shot capabilities. How can we explore LISA's zero-shot by zero-shot learning for specific tasks? Thank you very much!

Regards,

Dan
________________________________

**Comment by yxu1168** [comment]
Hi Xin,

I'd like to share a picture that LISA didn't do a good job: a picture of 4 former US presidents with their wives. LISA segmented 2 of them.
This tells the finetune is necessary and important for some specific tasks.
Also, people more like Zero-Shot. Can you please provide more detail of LISA's Zero-Shot? Thanks a lot!
Best regards,

Dan
[cid:b006cad8-690d-417a-b7a2-06965d487ff3]
________________________________
