### ISSUE TITLE
Questions about validation scripts

### ISSUE THREAD

**Issue by SxJyJay** [dvlab-research/LISA#65]
Hi, thanks for your great work.
I try to reproduce the training of LISA-7B following your instruction. However, I found that the [`train_ds.py`](https://github.com/dvlab-research/LISA/blob/main/train_ds.py) might cannot support valid evaluation because it seems that the pretrained model (i.e., the one saved as `pytorch_model.bin`) is not successfully loaded to the model. The evidence is that the `args.weight` is unused in the `train_ds.py`. To remedy this, I have tried to manually load the pretrained `pytorch_model.bin` by adding code below after [here](https://github.com/dvlab-research/LISA/blob/4b1776203d3410cd71b2d4720fc7d9cc61d1db3c/train_ds.py#L228):
```
if args.weight:
        state_dict = torch.load(args.weight, map_location="cpu")
        model.load_state_dict(state_dict, strict=True)
```
However, I still get abnormal results of "giou: 0.0317, ciou: 0.0200". Could you please help me to figure out where I am wrong?

**Comment by yxchng** [comment]
@SxJyJay have you solved the problem?

**Comment by X-Lai** [comment]
Sorry for late reply. I just fixed the bug, because we should not call initialize_lisa_module during validation. Now it works.
