### ISSUE TITLE
ResoningSeg Instructions

### ISSUE THREAD

**Issue by GuangyanS** [dvlab-research/LISA#7]
Great work!!!
I was wondering if you could shed some lights on how you guys annotate the reasoning segmentation image-instruction pairs.
Section 3.2 didn't elaborate much on the formulation of the text instructions.

**Comment by X-Lai** [comment]
We first manually raise questions involving reasoning and annotate the segmentation masks for 500-600 images. Then, we use these samples as seeds to prompt GPT to raise questions involving complex reasoning in a way similar to LLaVA. Also, considering the various errors and ambiguities in the generated questions, we further make a huge effort to manually filter them. For more details, you can refer to the paper of LLaVA.
