### ISSUE TITLE
Question about given checkpoints

### ISSUE THREAD

**Issue by jjungkang2** [dvlab-research/LISA#70]
What is the configuration for the provided checkpoints?

I've noticed some differences between the paper and the GitHub repository, such as variations in the dataset and whether the decoder was fine-tuned. I'd appreciate it if you could clarify whether the paper's version or the GitHub repository's version was followed.

**Comment by X-Lai** [comment]
Please refer to https://github.com/dvlab-research/LISA/issues/72.
