### ISSUE TITLE
A tiny doubt about the code "seg_token_mask" in the forward function of LISA model

### ISSUE THREAD

**Issue by SZhanZ** [dvlab-research/LISA#71]
Hello, thanks for your promising work and thorough opensource. 
I have a tiny doubt about the code in this line https://github.com/dvlab-research/LISA/blob/main/model/LISA.py#L187.
I puzzle about why you used  'input_ids[:, 1:] == self.seg_token_idx' instead of  'input_ids[:, 0:] == self.seg_token_idx'

**Comment by X-Lai** [comment]
We need a one-token offset such that the [SEG] token corresponds to the correct embedding.

**Comment by SxJyJay** [comment]
Could you please provide some cues about this "one-token offset" in the code? Thanks a lot!

**Comment by fengluo233** [comment]
> Could you please provide some cues about this "one-token offset" in the code? Thanks a lot!您能否提供有关代码中此“单标记偏移量”的一些提示？多谢！

Hi! Did your issue get resolved? I have a similar question: Why is the padding added from the end rather than the beginning?

**Comment by OedoSoldier** [comment]
This is due to the existence of the image token (i.e. "<image>").

You need to remove the image token before counting the index for the segmentation token:

https://github.com/dvlab-research/LISA/blob/dbe026abfdf2e15457d1f6849a21bd3c32b690eb/model/LISA.py#L187-L194

Then add the total patch token:

https://github.com/dvlab-research/LISA/blob/dbe026abfdf2e15457d1f6849a21bd3c32b690eb/model/LISA.py#L196C1-L199C10

**Comment by zhang-yige** [comment]
> This is due to the existence of the image token (i.e. "`<image>`" which `IMAGE_TOKEN_INDEX` is -200).
> 
> You need to remove the image token before counting the index for the segmentation token:
> 
> https://github.com/dvlab-research/LISA/blob/dbe026abfdf2e15457d1f6849a21bd3c32b690eb/model/LISA.py#L187-L194
> 
> Then add the masks for patch tokens:
> 
> https://github.com/dvlab-research/LISA/blob/dbe026abfdf2e15457d1f6849a21bd3c32b690eb/model/LISA.py#L196-L199

So does this mean that llama will automatically populate 255 tokens at \<image\> tokens?

**Comment by ojh6404** [comment]
In my understanding, within the next token prediction paradigm, I speculate that the token which outputs \<SEG\> token is the preceding one so we need to take last hidden states of previous one.
Am I wrong?

**Comment by OedoSoldier** [comment]
> In my understanding, within the next token prediction paradigm, I speculate that the token which outputs <SEG> token is the preceding one so we need to take last hidden states of previous one. Am I wrong?

![](https://i.imgur.com/U5YIE9n.png)

I explained this to my colleagues with this diagram: in an autoregressive (AR) model, the fundamental task is to predict the next token from the sequence of preceding tokens. This implies that the hidden state at a given position _i_ is not the representation of the input token at _i_. Rather, it's the representation generated after seeing the _i_-th token, which is then used to predict the (_i_+1)-th token.

Consequently, there is a one-step offset: `hidden_state[i]` is the representation for predicting `input_id[i+1]`.
