### ISSUE TITLE
Clarification Needed on Training Methods and Benchmark Results

### ISSUE THREAD

**Issue by tsunghan-wu** [dvlab-research/LISA#72]
Hello,

Firstly, I would like to express my appreciation for the excellent work on the LISA model. The paper provides insightful details, yet I find myself seeking further clarification regarding the benchmark results presented in the main text (Tables 1 & 2).

### Query about Training Configurations in Table 1:

a. For the model variant "LISA-7B" in Table 1, am I correct to understand that it is trained with the following configuration: "sem_seg\*9 + refer_seg\*3 + vqa\*3"?

b. Does "LISA-7B-ft" imply that the training configuration used is: "sem_seg\*9 + refer_seg\*3 + vqa\*3 + reason_seg (train)\*1"?

### Inquiries Regarding Training Configurations in Table 2:

a. Is "LISA-7B" trained with the configuration "sem_seg\*9 + vqa\*3"?

b. Conversely, does "LISA-7B-ft" denote a training configuration of "sem_seg\*9 + refer_seg\*3 + vqa\*3"?

### Discrepancy in Performance Metrics:

In a previous issue #56, it was mentioned that all v1 models (e.g., "LISA-7B-v1") were trained using the "sem_seg\*9 + refer_seg\*3 + vqa\*3 + reason_seg (train+val) \*1" configuration. However, my replication attempts using fp32 v1 models [(xinlai/LISA-7B-v1)](https://huggingface.co/xinlai/LISA-7B-v1) yield notably lower performance metrics: 67.24 cIoU on RefCOCO (val) and 60.88 cIoU on RefCOCOg (val), as opposed to the official results of 74.9 cIoU and 67.9 cIoU respectively. Even considering possible variations between v1 and v0, the gap appears somewhat significant. Could there be a possibility of overlooked aspects or unintended mistakes in the provided training details or implementation?

I am eagerly looking forward to your insights and clarification on these points. Thank you very much in advance!

**Comment by X-Lai** [comment]
@tsunghan-wu Thank you for your interest in our work. I feel very sorry to reply so late.

Here is some clarification:
Current released code is the refactored version, and thus is somewhat different from our initial experiments. More accurately, there are two differences in our initial experiments. 
First, in data sampling, we do not strictly follow 9:3:3:1, we uniformly select one dataset from 'ade20k||cocostuff||refer_seg||vqa||paco_lvis', and if we get 'refer_seg', then further select one from "refclef||refcoco||refcoco+||refcocog". So we roughly approximate with 9:3:3:1 in our refactored version. This difference should cause the result inconsistent.
Second, we set `lora_r`to 64 in our initial version, but later we find setting `lora_r` to 8 is slightly better for ReasonSeg, so we set it to 8 in our refactored version. But this setting may interfere the results in ReferSeg (i.e., refCOCO, etc.).
So, for someone who wants to completely reproduce the results, please restore these two differences.

For the results in Table 1: 
a. for the models w/o ft, we do not use reasoning segmentation dataset (i.e., 239 samples.), but the data sampling ratio is not strictly 9:3:3. For the concrete ratio, you may need to compute based on the above comments.
b. for the models w/ ft, we add reasoning segmentation dataset during training. Still, the data sampling ratio is not strictly 9:3:3:1.

For the results in Table 2:
a. for the model w/o ft, the model is completely the same with the model-7B (w/o ft) in Table 1.
b. for the model w/ ft, the model is completely trained with ReferSeg dataset (i.e., refCOCO/+/g).

Sorry for the inconvenience.
