### ISSUE TITLE
How to reproduce the results of refcoco

### ISSUE THREAD

**Issue by MaverickRen** [dvlab-research/LISA#74]
Since the paper does not describe what data the refcoco results were trained on, can you tell me how to reproduce this result? I cannot reproduce the results on refcoco by directly using the script in the repo. Thanks！

**Comment by Z-MU-Z** [comment]
@tsunghan-wu @X-Lai @MaverickRen Any updates on this? I still cannot reproduce the result in table2, using the given checkpoint. Can you give me some advice?

**Comment by Z-MU-Z** [comment]
I use [LISA-7B-v1](https://huggingface.co/xinlai/LISA-7B-v1) my result is below <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta><style> td {white-space:nowrap;border:1px solid #dee0e3;font-size:10pt;font-style:normal;font-weight:normal;vertical-align:middle;word-break:normal;word-wrap:normal;}</style><byte-sheet-html-origin data-id="1725279209014" data-version="4" data-is-embed="true" data-grid-line-hidden="false" data-copy-type="col">
LISA Reproduce |   |   | giou | ciou
-- | -- | -- | -- | --
refcoco | unc | val | 0.68 | 0.67
refcoco | unc | testA | 0.7 | 0.7
refcoco | unc | testB | 0.64 | 0.63
refcoco+ | unc | val | 0.53 | 0.54
refcoco+ | unc | testA | 0.6 | 0.59
refcoco+ | unc | testB | 0.46 | 0.47
refcocog | umd | val | 0.61 | 0.61
refcocog | umd | test | 0.62 | 0.62
ReasonSeg | split | val | 0.88 | 0.94

</byte-sheet-html-origin>

**Comment by PanXiongAdam** [comment]
hello, can you solve it?@Z-MU-Z 
I get the same score
