### ISSUE TITLE
how to validate LISA-13B-llama2-v0?

### ISSUE THREAD

**Issue by yxchng** [dvlab-research/LISA#75]
I tried downloading the model and it has pytorch_model-000001-of-000003.bin, pytorch_model-000001-of-000003.bin, pytorch_model-000002-of-000003.bin, instead of of a single pytorch_model.bin.

<img width="1028" alt="Screen Shot 2023-10-19 at 1 00 22 AM" src="https://github.com/dvlab-research/LISA/assets/10518587/1a4859df-18ac-40bf-bf1c-c12a4e93b3f6">

However, when I tried to validate following the validation instruction using the command:

```
deepspeed --master_port=24999 train_ds.py \
  --version="models/LISA-13B-llama2-v0" \
  --dataset_dir='./dataset' \
  --vision_pretrained="sam_vit_h_4b8939.pth" \
  --exp_name="lisa-7b" \
  --weight='models/LISA-13B-llama2-v0/pytorch_model.bin' \
  --eval_only
```

and met file not found error. Passing `--weight='models/LISA-13B-llama2-v0/` gives error too. What did I do wrong? How can I get a single pytorch_model.bin that can be passed for the weight argument?

**Comment by X-Lai** [comment]
Please ignore the `weight` argument, and in the latest version of the repo, there is no `weight` argument in the `train_ds.py` file.
