### ISSUE TITLE
Questions about LISA

### ISSUE THREAD

**Issue by nqx12348** [dvlab-research/LISA#78]
Congratulations on your great success! 

I have some question about LISA:

1. In table 1 of the paper, we can find that LISA achieves better performance on the ResonSeg val set for both zero-shot and finetuned settings, outperforming 4 segmentation models.  Are these existing models using for comparison (OVSeg, GRES, X-Decoder, SEEM) trained on the same data (i.e., Semantic/refering segmentation data enhanced with template, VQA data) as LISA before testing on the val set? 

I'm curious whether a vanilla segmentation model (without LLM) could handle the reasoning segmentation task after trained on reasoning segmentation data, and how much LLM contributed to LISA's outstanding performance in this task.

2. I notice that LISA can segment lisa (an idol from Thailand) properly, which is quite suprising for me. How could LISA have such an ability? Is this because the photo of lisa occurs in the Reasoning segmentation data (semantic/refering segmentation +vqa data + ReasonSeg), or in LLaVA training data?  Or this relies on the generalization ability of SAM? Could you explain it a little bit? Thanks!

Looking forward to your reply!

![image](https://github.com/dvlab-research/LISA/assets/34655289/f17f876e-3a8c-481d-8f32-a2587b9c3e01)

**Comment by X-Lai** [comment]
1. We use the officially released model weights of the 4 existing methods for evaluation. They may use different data from ours, but all of us mainly use the coco images. 
2. The reasoning segmentation dataset does not contain the sample of 'Lisa'. It might appear in the pre-training dataset of LLaVA or CLIP.
