### ISSUE TITLE
pascal_part train.json

### ISSUE THREAD

**Issue by AmeenAli** [dvlab-research/LISA#8]
Thanks for sharing this work!

One question, where can i get the train.json file for pascal_part + is VOCdevkit the one for pascal 2010 or 2012?

Thanks!

**Comment by X-Lai** [comment]
Sorry to directly copy the official download page. Please follow the guidance here: https://github.com/facebookresearch/VLPart/tree/main/datasets#pascal-part. I will fix README.md right now.
