### ISSUE TITLE
Validate on my own trained pytorch.bin

### ISSUE THREAD

**Issue by baoxiaoyi** [dvlab-research/LISA#86]
Great work! I follow your lisa-7b-v0 setting,and transfer my ckpt into the pytorch.bin following your instruction. How to use my own pytorch.bin for validation? 
1. Maybe I should change the PATH_TO_LISA_HF to my own path, then how to produce the other file like config.json?
2. Should I use the following command to validate? I try like that and meet unexpected param in ckpt for PEFTLISACausal model, especially those of visual_model.
`deepspeed --master_port=24999 train_ds.py \
  --version="PATH_TO_LISA_HF_Model_Directory" \
  --dataset_dir='./dataset' \
  --vision_pretrained="PATH_TO_SAM" \
  --exp_name="lisa-7b" \
  --eval_only`

**Comment by baoxiaoyi** [comment]
Solved! Same as #65. I updated the code to the newest version without call initialize_lisa_module during the validation. Thanks

**Comment by Syn000** [comment]
Hello, I still meet unexpected param in ckpt for PEFTLISACausal model after adding the codes like #65 . May I ask how you change the command when loading your pytorch.bin file?
