### ISSUE TITLE
Fine-tune

### ISSUE THREAD

**Issue by dhhxhhh** [dvlab-research/LISA#9]
Is there any finetune code?

**Comment by X-Lai** [comment]
There is only a single finetuning state. The reasoning segmentation dataset is directly involved with other datasets like the semantic / referring segmentation datasets.

**Comment by dhhxhhh** [comment]
> There is only a single finetuning state. The reasoning segmentation dataset is directly involved with other datasets like the semantic / referring segmentation datasets.

emm,I want to employ the LISA to conduct the image-caption task, whose generated caption is more detailed than other model. But there is a domain difference between the train dataset and industrial dataset, so I wanna finetune LISA to apply to industrial domain.

**Comment by X-Lai** [comment]
That sounds grea

**Comment by X-Lai** [comment]
That sounds great! You can add your customized data into the current training pipeline by simply configuring the `dataset` argument. As you want to use VQA data to conduct the image-caption task, I think you can directly replace the current `llava-instruct-150k` dataset with yours by simply configuring the `vqa_data` argument in `train_ds.py`.

Currently, we do not plan to release the code to further fine-tuning LISA. I think you could try to use the current hybrid-training paradigm together with other datasets.

**Comment by SiyuanHuang95** [comment]
> 

How about opening some layers or enabling the finetuning some parameters of the original LISA, do you think it would be doable? @X-Lai
