### ISSUE TITLE
Question about [start_token]

### ISSUE THREAD

**Issue by CoderZhangYx** [dvlab-research/LISA#92]
Hi, thanks for your terrific work!
During reading your code, I found that in https://github.com/dvlab-research/LISA/blob/7232bb8fa764f6d3a9b7928c975e26a67fde545c/model/LISA.py#L187 and in https://github.com/dvlab-research/LISA/blob/7232bb8fa764f6d3a9b7928c975e26a67fde545c/utils/dataset.py#L99, [START_TOKEN] (or [CLS_TOKEN] in some works) is consiered. However, the constructed text-prompt data seems to not have such a token.
Did I ignore some related codes?  Did i misunderstand your code?
Any explanation would be helpful, thanks!

**Comment by CoderZhangYx** [comment]
I found that CLIP tokeizer will automatically add one [start_token], but the other tokenizer i load did not do this, which is where the problem lies in

**Comment by fengluo233** [comment]
> I found that CLIP tokeizer will automatically add one [start_token], but the other tokenizer i load did not do this, which is where the problem lies in我发现 CLIP tokeizer 会自动添加一个 [start_token]，但我加载的另一个分词器没有这样做，这就是问题所在

Hello, I’m encountering a related issue: the line assert cur_len == total_len in my code fails the check in certain cases, and the lengths of the two differ by only 1. Could this be the reason? I would greatly appreciate your assistance if possible. My WeChat ID is 15623738929.
